# Generated by the vetiver package; edit with care
library(googleCloudStorageR)
library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_gcs("info-4940-models", prefix = "skillful-wombat/")
v <- vetiver_pin_read(b, "poisson-nys-crime", version = "20241216T061552Z-ec84d")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
